# Generated by Django 5.1.3 on 2024-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'İletişim Bilgileri', 'verbose_name_plural': 'İletişim Bilgileri'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
