# Generated by Django 5.1.3 on 2024-11-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='İsim')),
                ('surname', models.CharField(max_length=20, verbose_name='Soyisim')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                ('date_time', models.DateTimeField(unique=True, verbose_name='Tarih ve Saat')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
            },
        ),
    ]
