# Generated by Django 5.2.3 on 2025-06-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati'),
        ),
    ]
