# Generated by Django 5.2.3 on 2025-06-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(default='000000000', max_length=15, verbose_name='Telefon Numarası'),
        ),
    ]
