# Generated by Django 4.2.30 on 2026-08-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Rezerve Edildi'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], db_index=True, default='BOOKED', max_length=20)),
                ('client_notes', models.TextField(blank=True, default='')),
                ('psychologist_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Uzman Klinik Psikolog', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=50, help_text='Seans süresi (dakika)')),
                ('break_duration_minutes', models.PositiveIntegerField(default=10, help_text='Mola süresi (dakika)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psikolog',
                'verbose_name_plural': 'Psikologlar',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], db_index=True, default='PENDING', max_length=20)),
                ('created_by_psychologist', models.BooleanField(default=False, help_text='Psikolog tarafından manuel mi oluşturuldu')),
                ('notes', models.TextField(blank=True, default='', help_text='Psikoloğun danışan ile ilgili özel notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danışan Profili',
                'verbose_name_plural': 'Danışan Profilleri',
            },
        ),
        migrations.CreateModel(
            name='CancelledAppointmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_by', models.CharField(default='PSYCHOLOGIST', max_length=20)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('client_notified', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_log', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'İptal Edilen Randevu Kaydı',
                'verbose_name_plural': 'İptal Edilen Randevu Kayıtları',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.clientprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.psychologist'),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')])),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('is_active', models.BooleanField(default=True, help_text='Bu gün seans kabul ediliyor mu?')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='appointments.psychologist')),
            ],
            options={
                'verbose_name': 'Haftalık Çalışma Şablonu',
                'verbose_name_plural': 'Haftalık Çalışma Şablonları',
                'ordering': ['day_of_week'],
                'unique_together': {('psychologist', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('override_type', models.CharField(choices=[('OFF', 'İzinli / Kapalı'), ('CUSTOM', 'Özel Çalışma Saatleri')], default='OFF', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='appointments.psychologist')),
            ],
            options={
                'verbose_name': 'Özel Gün / İstisna',
                'verbose_name_plural': 'Özel Günler / İstisnalar',
                'unique_together': {('psychologist', 'date')},
            },
        ),
    ]
