# Generated by Django 4.2.30 on 2026-08-25 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('CHANGE_PHONE', 'Telefon Değiştirme'), ('CHANGE_EMAIL', 'E-posta Değiştirme'), ('CHANGE_PASSWORD', 'Şifre Değiştirme')], max_length=30)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-posta Doğrulama Kodu',
                'verbose_name_plural': 'E-posta Doğrulama Kodları',
                'ordering': ['-created_at'],
            },
        ),
    ]
