# Generated by Django 4.2.30 on 2026-09-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Aybike Yaren Topcuoğlu', max_length=150, verbose_name='Ad Soyad')),
                ('title', models.CharField(default='Psikolog ve Aile Danışmanı', max_length=150, verbose_name='Unvan')),
                ('profile_image', models.TextField(blank=True, default='', verbose_name='Profil Fotoğrafı (Base64 veya URL)')),
                ('about_text', models.TextField(default='Ben Aybike Yaren Topcuoğlu, Psikolog ve Aile Danışmanıyım. Lisans eğitimimi Sakarya Üniversitesi Psikoloji Bölümü’nde yüksek onur derecesi ile tamamladım. Şu anda Haliç Üniversitesi Tezli Psikoloji Yüksek Lisans Programı’nda uzmanlık eğitimime devam etmekteyim. Akademik hayatım boyunca araştırma projeleri, makale ve kitap çalışmaları içerisinde yer aldım; aynı zamanda birçok eğitim ve seminer vererek mesleki deneyimimi zenginleştirdim.\n\nMesleki pratiğimde hem yetişkinlerle hem de çocuklarla çalışıyorum. Yetişkin danışanlarla özellikle duygudurum bozuklukları, kaygı (anksiyete) bozuklukları, obsesif kompulsif bozukluk, öfke kontrol güçlükleri, somatik bozukluklar, yeme bozuklukları üzerine yoğunlaşıyorum. Ayrıca aile ve ebeveyn danışmanlığı alanında da aktif olarak çalışmaktayım.\n\nTerapötik yaklaşımımda tek bir yönteme bağlı kalmaktan ziyade danışanın ihtiyacına göre farklı ekolleri bir araya getirmeyi önemsiyorum. Dinamik ve derinlemesine bakış açısını şefkatli bir şekilde harmanlarken, yapılandırılmış teknikleri de sürecin içine katıyorum. Böylece hem iç dünyadaki kök nedenlere dokunabilmeyi hem de gündelik yaşamda işlevselliği artırmayı hedefliyorum.\n\nBugüne kadar iki anaokulunda kurum psikoloğu olarak görev aldım, atölye çalışmaları düzenledim ve çocuk, ergen, yetişkin danışanlarla klinik deneyim kazandım. Aynı zamanda topluluk çalışmalarım, deprem sonrası psikososyal destek faaliyetlerim ve hastane okulu projelerim bana çok yönlü bir saha deneyimi kattı.\n\nMesleğe bakışımda en çok önem verdiğim şey; insanın içsel yolculuğunda yanında güvenle eşlik edebilmek. Her bireyin kendi hikâyesiyle değerli olduğuna inanıyor ve bu yolculukta bilimsel, etik ve insancıl bir yaklaşımı rehber ediniyorum.', verbose_name='Hakkımda Metni')),
                ('contact_email', models.EmailField(default='psikologaybikeyaren@gmail.com', max_length=254, verbose_name='İletişim E-postası')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='İletişim Telefonu')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adres')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/psikologaybiketopcuoglu', verbose_name='Instagram Linki')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn Linki')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Sayfa İçerikleri (Hakkımda & İletişim)',
                'verbose_name_plural': 'Sayfa İçerikleri',
            },
        ),
    ]
